# Generated by Django 4.2.7 on 2023-11-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('course', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.FileField(upload_to='main/')),
                ('player_f_name', models.CharField(max_length=255)),
                ('player_f_status', models.CharField(max_length=255)),
                ('player_s_name', models.CharField(max_length=255)),
                ('player_s_status', models.CharField(max_length=255)),
                ('watch_button', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.URLField(max_length=255)),
                ('news', models.URLField(max_length=255)),
                ('courses', models.URLField(max_length=255)),
                ('library', models.URLField(max_length=255)),
                ('search', models.URLField(max_length=255)),
                ('basket', models.URLField(max_length=255)),
                ('bell', models.URLField(max_length=255)),
                ('login', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TopCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_all_button', models.URLField()),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='TopBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_watching', models.IntegerField()),
                ('book_all_button', models.URLField()),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.library')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
    ]
